name: Build and test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Cache node_modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ubuntu-latest-node-v15.x-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Cache node_modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ubuntu-latest-node-v15.x-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - run: npm run lint

  test-unit:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Cache node_modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ubuntu-latest-node-v15.x-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - run: npm run test:unit

  test-e2e:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Cache node_modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ubuntu-latest-node-v15.x-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - run: npx cypress install
      - run: npm run test:e2e
